<?php

    namespace papalapa\yiistart\models;

    /**
     * Class Mailer
     * @package papalapa\yiistart\models
     */
    class Mailer extends \yii\swiftmailer\Mailer
    {
        public function send($message)
        {
            if (!array_key_exists('from', $this->messageConfig)) {
                $this->messageConfig['from'] = [\Yii::$app->params['noreply.email'] => \Yii::$app->name.' robot'];
            }

            return parent::send($message); // TODO: Change the autogenerated stub
        }
    }
